In [1]:
import gym
class Agent:
    def __init__(self,env):
        self.actionNumber=env.action_space.n
        
    def getAction(self, state):
        angle=state[2]
        if (angle<0):
            return 0
        elif (angle>0):
            return 1

In [2]:
env = gym.make('CartPole-v0')
a=Agent(env)
for j in range(10):
    state=env.reset()
    for i in range(10000):
        state, reward, done, info=env.step(a.getAction(state)) # take a random action
        env.render()
        print(state)
        if (done):
            print("No .of steps "+str(i))
            break
            
env.close()

[ 0.04444062 -0.2103429  -0.02956742  0.24839814]
[ 0.04023376 -0.40503039 -0.02459945  0.53161018]
[ 0.03213315 -0.59979785 -0.01396725  0.81644147]
[ 0.0201372  -0.79472581  0.00236158  1.10469866]
[ 0.00424268 -0.599635    0.02445555  0.81275756]
[-0.00775002 -0.4048564   0.0407107   0.52786624]
[-0.01584715 -0.21033017  0.05126803  0.2482843 ]
[-0.02005375 -0.01597645  0.05623371 -0.02779703]
[-0.02037328  0.17829586  0.05567777 -0.30222087]
[-0.01680736  0.3725819   0.04963336 -0.57683751]
[-0.00935572  0.5669743   0.03809661 -0.85348081]
[ 0.00198376  0.76155683  0.02102699 -1.13394514]
[ 0.0172149   0.95639739 -0.00165191 -1.41995988]
[ 0.03634285  0.76129591 -0.03005111 -1.12779374]
[ 0.05156876  0.56658026 -0.05260699 -0.84468582]
[ 0.06290037  0.3722141  -0.0695007  -0.56899924]
[ 0.07034465  0.17813223 -0.08088069 -0.29899603]
[ 0.0739073  -0.01574927 -0.08686061 -0.0328775 ]
[ 0.07359231 -0.20952515 -0.08751816  0.2311856 ]
[ 0.06940181 -0.4032946  -0.08289445  0.49502986]


[ 0.0029658   0.61399751  0.02272532 -0.86189345]
[ 0.01524575  0.80880277  0.00548745 -1.14734522]
[ 0.03142181  1.00385264 -0.01745946 -1.43830232]
[ 0.05149886  0.80895015 -0.0462255  -1.15112595]
[ 0.06767786  0.61446084 -0.06924802 -0.87328909]
[ 0.07996708  0.42034536 -0.0867138  -0.60315636]
[ 0.08837399  0.22653641 -0.09877693 -0.33899716]
[ 0.09290472  0.03294857 -0.10555687 -0.07902407]
[ 0.09356369 -0.16051426 -0.10713736  0.17857884]
[ 0.0903534  -0.35395292 -0.10356578  0.43563499]
[ 0.08327434 -0.54746799 -0.09485308  0.69395834]
[ 0.07232499 -0.74115513 -0.08097391  0.95533805]
[ 0.05750188 -0.93510004 -0.06186715  1.22152187]
[ 0.03879988 -1.12937265 -0.03743671  1.49419594]
[ 0.01621243 -1.32401978 -0.00755279  1.77495823]
[-0.01026797 -1.51905582  0.02794637  2.06528344]
[-0.04064908 -1.3242293   0.06925204  1.78137294]
[-0.06713367 -1.12995119  0.1048795   1.51099813]
[-0.08973269 -0.93624451  0.13509946  1.25281276]
[-0.10845758 -0.74308675  0.16015572  1.00531474]


[-0.05689234  0.75457203  0.04033709 -1.03116444]
[-0.0418009   0.9491348   0.01971381 -1.3109153 ]
[-0.0228182   1.14400161 -0.0065045  -1.59736324]
[ 6.18296009e-05  9.48957351e-01 -3.84517653e-02 -1.30671535e+00]
[ 0.01904098  0.75434332 -0.06458607 -1.02631211]
[ 0.03412784  0.56013792 -0.08511231 -0.75458648]
[ 0.0453306   0.366286   -0.10020404 -0.489854  ]
[ 0.05265632  0.17270984 -0.11000112 -0.23035701]
[ 0.05611052 -0.02068237 -0.11460826  0.02570286]
[ 0.05569687 -0.21399013 -0.11409421  0.28014113]
[ 0.05141707 -0.40731533 -0.10849138  0.53477256]
[ 0.04327076 -0.6007578  -0.09779593  0.79139634]
[ 0.03125561 -0.79441072 -0.08196801  1.05178154]
[ 0.01536739 -0.98835562 -0.06093238  1.31765052]
[-0.00439972 -1.1826563  -0.03457937  1.59065763]
[-0.02805285 -1.37735104 -0.00276621  1.87236085]
[-0.05559987 -1.57244267  0.034681    2.16418391]
[-0.08704872 -1.37767639  0.07796468  1.88240434]
[-0.11460225 -1.18348498  0.11561277  1.61490048]
[-0.13827195 -0.98990134  0.147910

In [6]:
import numpy as np
print(np.random.random([10,10]))

[[0.24945171 0.8963387  0.74419196 0.14560902 0.74455198 0.40820859
  0.37349634 0.77972454 0.48959364 0.42658084]
 [0.20975207 0.23383949 0.83314702 0.63206065 0.13736056 0.79354209
  0.35035214 0.99630161 0.22724255 0.59324851]
 [0.54973124 0.40611243 0.02309339 0.63127557 0.76625887 0.39813927
  0.57180881 0.12846641 0.36158092 0.3223563 ]
 [0.86001114 0.62016085 0.59167676 0.68615146 0.93695532 0.3829822
  0.21384259 0.58547943 0.4665391  0.80983115]
 [0.82528808 0.58732938 0.33280859 0.62988309 0.57888423 0.22268668
  0.31366525 0.71274263 0.9832682  0.97386605]
 [0.79383    0.31581425 0.72692858 0.19038204 0.60455074 0.79681836
  0.94394204 0.27061312 0.36720087 0.65502724]
 [0.97770599 0.55749306 0.13805783 0.02844628 0.0158986  0.71514575
  0.82729359 0.44040717 0.89156284 0.70151627]
 [0.49932378 0.68007803 0.23390726 0.08446086 0.81637515 0.145165
  0.83926578 0.63806137 0.28264376 0.37398302]
 [0.29479666 0.21084062 0.4234797  0.41666205 0.959328   0.57412025
  0.33560218 0.